# Puerto personalizado
server.port=9090

# H2 Database (Guarda la BD en una carpeta "base_datos" junto al ejecutable)
spring.datasource.url=jdbc:h2:file:./base_datos/dxyopdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (accede en http://localhost:9090/h2-console)
spring.h2.console.enabled=true

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Cerrar sesión automáticamente tras 10 minutos de inactividad
server.servlet.session.timeout=10m