# Puerto personalizado
server.port=9090

# ==========================================
# 1. CONEXIÓN A BASE DE DATOS (POSTGRESQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/dxyopdb
spring.datasource.username=postgres
# PON AQUÍ LA CONTRASEÑA QUE LE PUSISTE A POSTGRESQL AL INSTALARLO:
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# 2. CONFIGURACIÓN DE HIBERNATE (ORM)
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# update: Crea tablas nuevas y respeta los datos existentes (BLINDAJE)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# 3. LOGGING Y SESIÓN
# ==========================================
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Cerrar sesión automáticamente tras 1 hora de inactividad
server.servlet.session.timeout=1h

# ==========================================
# RESPALDO DE H2 (COMENTADO)
# ==========================================
# spring.datasource.url=jdbc:h2:file:./base_datos/dxyopdb;AUTO_SERVER=TRUE
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true